Repository mehalyna/Ch-117-Python-Project-ITA, pull requests merged in 2021-06, with the labels that each got.

#305 change name of news footer
  library/catalog/templates/base.html
Labels: Task

#306 added author statistic
  library/catalog/static/css/main.css
  library/catalog/templates/authors.html
  library/catalog/views.py
Labels: Task

#311 Add favicon
  library/catalog/static/images/favicon.svg
  library/catalog/templates/base.html
Labels: Task, enhancement

#316 fix bug with reset password
  library/catalog/views.py
Labels: bug

#315 Fix bugs with comment UI
  library/catalog/static/js/bookDetails.js
Labels: bug

#318 Donate custom price
  library/catalog/static/js/payments_metod.js
  library/catalog/templates/donate_page.html
  library/catalog/views.py
Labels: Task

#321 changed url to redirect after push the "back" button on the book deta…
  library/catalog/templates/book-details.html
Labels: bug

#320 Saving book statistic
  library/catalog/views.py
Labels: bug

#322 Fix bug with comment time
  library/catalog/migrations/0002_auto_20210601_1858.py
  library/catalog/models.py
Labels: bug

#323 Fix empty review error message
  library/catalog/static/css/main.css
  library/catalog/static/js/bookDetails.js
  library/catalog/templates/book-details.html
  library/catalog/views.py
Labels: bug

#317 'donate UI'
  library/catalog/static/css/main.css
  library/catalog/static/images/green-tick.svg
  library/catalog/static/images/heart.svg
  library/catalog/static/images/red-cross.png
  library/catalog/templates/base.html
  library/catalog/templates/cancel.html
  library/catalog/templates/donate_page.html
  library/catalog/templates/home.html
  library/catalog/templates/success.html
Labels: Task

#332 Add moderator abilities
  library/catalog/static/js/bookDetails.js
Labels: bug

#329 Fix help mail csrftoken exception
  library/catalog/views.py
Labels: bug

#327 Help form margin bottom
  library/catalog/templates/help_email.html
Labels: bug

#326 Show reviews for unathorized user
  library/catalog/static/css/main.css
  library/catalog/templates/book-details.html
Labels: bug

#324 UI improvements
  library/catalog/templates/base.html
  library/catalog/templates/reset_password.html
Labels: Task

#331 changed title on the authors page
  library/catalog/templates/authors.html
Labels: bug

#333 Show text if reviews list is empty
  library/catalog/templates/book-details.html
Labels: bug

#336 moved the caption review
  library/catalog/templates/book-details.html
Labels: bug

#338 fixed import file
  admin/app.py
Labels: bug

#339 Admin panel fix search
  admin/utils.py
Labels: bug
