Repository mehalyna/Ch-117-Python-Project-ITA, pull requests merged in 2021-04, with the labels that each got.

#63 change opacity for restore user btn
  admin/templates/users_list.html
Labels: Task

#65 UI for file import
  admin/templates/csv-import.html
Labels: Task

#64 User managment validation
  .gitignore
  admin/app.py
  admin/forms.py
  admin/templates/create_user.html
  admin/templates/update_user.html
Labels: Task

#66 Import file validation
  admin/app.py
  admin/templates/csv-import.html
Labels: Task

#69 User management UI
  admin/forms.py
  admin/static/css/style.css
  admin/static/js/main.js
  admin/templates/base.html
  admin/templates/create_user.html
  admin/templates/update_user.html
  admin/templates/users_list.html
Labels: Task

#70 Fix reference field problem
  admin/app.py
  admin/forms.py
  admin/models.py
  admin/templates/add-book.html
  admin/templates/book-active.html
  admin/templates/book-details.html
  admin/templates/book-inactive.html
  admin/templates/book-storage.html
  admin/templates/update-book.html
Labels: Task

#78 User edit UI
  admin/app.py
  admin/static/js/main.js
  admin/templates/update_user.html
Labels: Task

#81 Home page UI
  admin/app.py
  admin/templates/index.html
Labels: Task

#79 Load books from json file
  admin/app.py
  admin/templates/csv-import.html
Labels: Task

#83 Book details UI
  admin/app.py
  admin/static/css/style.css
  admin/static/images/readingNow.png
  admin/static/images/totalRead.png
  admin/static/js/main.js
  admin/templates/book-details.html
Labels: Task

#84 Refactor pagination
  admin/app.py
  admin/static/css/style.css
Labels: bug

#91 Book details UI
  admin/templates/book-details.html
Labels: Task

#94 Book image link
  admin/app.py
  admin/forms.py
  admin/templates/add-book.html
  admin/templates/update-book.html
Labels: Task

#92 Spaces in import file example
  admin/templates/csv-import.html
Labels: Task

#98 Book storage UI
  admin/static/css/style.css
  admin/templates/book-storage.html
Labels: bug

#96 Users search fix
  admin/app.py
  admin/forms.py
  admin/static/css/style.css
  admin/static/js/main.js
  admin/templates/update_user.html
  admin/templates/users_list.html
  admin/utils.py
Labels: bug

#103 #102-Locked functionality for change status and role for admin
  admin/app.py
Labels: Task

#101 #100-Fixed work with genres
  admin/app.py
  admin/templates/book-details.html
  admin/templates/update-book.html
Labels: Task

#104 Books search fix
  admin/app.py
  admin/static/css/style.css
  admin/static/js/main.js
  admin/templates/book-details.html
  admin/templates/book-storage.html
  admin/templates/update-book.html
  admin/templates/update_user.html
  admin/templates/users_list.html
  admin/utils.py
Labels: bug

#105 sorting by field via search authors
  admin/utils.py
Labels: bug

#106 search algorythm refactor
  admin/utils.py
Labels: bug

#107 fixed editing & deleting condition
  admin/app.py
Labels: bug

#117 Django skeleton
  .gitignore
  admin/app.py
  library/catalog/__init__.py
  library/catalog/admin.py
  library/catalog/apps.py
  library/catalog/migrations/__init__.py
  library/catalog/models.py
  library/catalog/tests.py
  library/catalog/urls.py
  library/catalog/views.py
  library/library/__init__.py
  library/library/asgi.py
  library/library/settings.py
  library/library/urls.py
  library/library/wsgi.py
  library/manage.py
  requirements.txt
Labels: Task

#116 Upload file test
  admin/tests/test_data/books.json
  admin/tests/test_unit/test_routes/app.py
  admin/tests/test_unit/test_routes/test_file_upload_form.py
Labels: Task

#118 Test create user
  admin/app.py
  admin/tests/test_unit/test_forms/test_create_user_form.py
  admin/tests/test_unit/test_forms/test_login_form.py
  admin/tests/test_unit/test_models/test_author_model.py
  admin/tests/test_unit/test_routes/app.py
  admin/tests/test_unit/test_routes/test_book_storage.py
  admin/tests/test_unit/test_routes/test_create_user.py
  admin/tests/test_unit/test_routes/urls.py
  requirements.txt
Labels: Task

#126 #119 test project refactoring
  admin/app.py
  admin/tests/test_unit/test_models/test_author_model.py
  admin/tests/test_unit/test_routes/app.py
Labels: bug

#127 Registration page UI
  admin/tests/test_unit/test_models/test_author_model.py
  library/catalog/forms.py
  library/catalog/static/css/main.css
  library/catalog/static/images/envelope-square-solid.png
  library/catalog/static/images/envelope-square-solid.svg
  library/catalog/static/images/key-solid.png
  library/catalog/static/images/key-solid.svg
  library/catalog/static/images/sign-in-alt-solid.png
  library/catalog/static/images/sign-in-alt-solid.svg
  library/catalog/static/images/user-plus.png
  library/catalog/static/images/user-solid.png
  library/catalog/static/images/user-solid.svg
  library/catalog/templates/registration.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
  library/library/urls.py
Labels: Task

#128 Base page
  library/catalog/static/images/search.png
  library/catalog/static/images/user-regular.svg
  library/catalog/templates/base.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#130 Form validation
  library/catalog/forms.py
  library/catalog/models.py
  library/catalog/templates/registration.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#135 registration extending base.html
  library/catalog/static/css/main.css
  library/catalog/templates/base.html
  library/catalog/templates/registration.html
Labels: Task

#129 #122-implemented books' details page
  library/catalog/models.py
  library/catalog/static/css/main.css
  library/catalog/static/images/readingNow.png
  library/catalog/static/images/totalRead.png
  library/catalog/templates/base.html
  library/catalog/templates/book-details.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task, help wanted

#138 #131-Block of comments
  library/catalog/models.py
  library/catalog/static/css/main.css
  library/catalog/templates/book-details.html
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#137 Registration form client side validation
  library/catalog/models.py
  library/catalog/static/css/main.css
  library/catalog/static/js/registrationForm.js
  library/catalog/templates/registration.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#141 home-page-improvements
  library/catalog/static/css/main.css
  library/catalog/templates/base.html
  library/catalog/templates/home.html
  library/catalog/templates/registration.html
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#146 Block of comments
  library/catalog/static/css/main.css
  library/catalog/templates/book-details.html
Labels: Task, enhancement

#143 Registration input storage
  library/catalog/static/js/registrationForm.js
  library/catalog/templates/registration.html
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#151 Registration server side profanity filter
  library/catalog/forms.py
  requirements.txt
Labels: Task

#154 registration client side profanity validation
  library/catalog/static/js/registrationForm.js
Labels: Task

#157 Registration white space validation
  library/catalog/static/js/registrationForm.js
  library/catalog/views.py
Labels: Task

#153 Profile_bookshelf-UI
  library/catalog/static/css/main.css
  library/catalog/templates/base_profile.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#159 #137-created page 'Search result'
  library/catalog/static/css/main.css
  library/catalog/templates/book-details.html
  library/catalog/templates/books.html
Labels: Task

#150 Authentication
  admin/models.py
  library/catalog/forms.py
  library/catalog/migrations/__init__.py
  library/catalog/models.py
  library/catalog/templates/profile_details.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
  library/library/urls.py
Labels: Task
