Repository mehalyna/Ch-117-Python-Project-ITA, pull requests merged in 2021-05, with the labels that each got.

#167 #166-Added functionality for book details page
  library/catalog/templates/book-details.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#165 #164-Added functionality for sliders on the home page
  library/catalog/forms.py
  library/catalog/templates/home.html
Labels: Task

#163 #160-Added dynamic loading of genres from the database
  library/catalog/templates/books.html
  library/catalog/templates/home.html
  library/catalog/views.py
  library/library/settings.py
Labels: Task, enhancement

#172 #171-Rating of books
  library/catalog/models.py
  library/catalog/templates/book-details.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task, enhancement

#170 Auth django user
  .gitignore
  library/catalog/forms.py
  library/catalog/models.py
  library/catalog/static/js/main.js
  library/catalog/templates/base.html
  library/catalog/templates/login_redirect.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Priority-0, Task

#175 Client side registration validation fix
  library/catalog/static/js/registrationForm.js
Labels: bug

#178 User authorization after a successful registration
  library/catalog/views.py
Labels: Task

#183 Clear local storage after a successful registration
  library/catalog/views.py
Labels: Task

#185 #179 - fixed bug, refactored code
  library/catalog/models.py
  library/catalog/templates/book-details.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#196 Fixing adding rating by user
  library/catalog/models.py
  library/catalog/static/js/bookDetails.js
  library/catalog/templates/book-details.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: bug

#199 Fixed add comment button flex
  library/catalog/templates/book-details.html
Labels: bug

#203 Changed user icon class
  library/catalog/static/css/main.css
  library/catalog/templates/base.html
Labels: bug

#201 Fixed book details functions
  library/catalog/views.py
Labels: bug

#205 Fixed ConnectionAbortedError
  library/catalog/static/js/bookDetails.js
  library/catalog/views.py
Labels: bug

#195 #192 - Add functionality for wishlist (add and delete books)
  library/catalog/static/css/main.css
  library/catalog/templates/book-details.html
  library/catalog/templates/profile_bookshelf.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#212 Fix book details functions
  library/catalog/templates/book-details.html
  library/catalog/views.py
Labels: bug

#215 Add login require to book details functions
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#213 Error message if blank comment
  library/catalog/static/css/main.css
  library/catalog/static/js/bookDetails.js
  library/catalog/templates/book-details.html
  library/catalog/views.py
Labels: bug

#218 Auth error message
  library/catalog/static/css/main.css
  library/catalog/static/js/main.js
  library/catalog/static/js/redirect_login.js
  library/catalog/templates/base.html
  library/catalog/templates/login_redirect.html
Labels: Task

#221 Frontend edit user validation
  library/catalog/static/js/changePasswordForm.js
  library/catalog/static/js/editUserForm.js
  library/catalog/templates/change_password.html
  library/catalog/templates/profile_edit.html
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#226 Auth UI fix
  library/catalog/templates/base.html
  library/catalog/templates/login_redirect.html
  library/catalog/views.py
Labels: Task

#239 Registration test
  library/catalog/tests/test_forms.py
  library/catalog/tests/test_views.py
Labels: Task

#246 #244 - added tests for page 'book details'
  library/catalog/tests/test_views.py
Labels: Task, Test

#247 #236 - fix books counter 'total read' and 'reading now'
  library/catalog/views.py
Labels: bug

#248 #224 - system use deleted books (fixed)
  library/catalog/views.py
Labels: bug

#255 Fix book details back button
  library/catalog/templates/book-details.html
  library/catalog/views.py
Labels: bug

#254 Custom user model
  .gitignore
  library/catalog/forms.py
  library/catalog/migrations/0001_initial.py
  library/catalog/models.py
  library/catalog/views.py
  library/library/settings.py
  requirements.txt
Labels: Task

#258 Password recovery
  library/catalog/forms.py
  library/catalog/migrations/0001_initial.py
  library/catalog/models.py
  library/catalog/templates/base.html
  library/catalog/templates/password_reset.html
  library/catalog/templates/password_reset_complete.html
  library/catalog/templates/password_reset_form.html
  library/catalog/templates/password_reset_sent.html
  library/catalog/templates/profile_details.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#256 Views code refactor to user model
  library/catalog/views.py
Labels: Task

#263 Django models fix
  library/catalog/migrations/0001_initial.py
  library/catalog/models.py
Labels: Task

#268 Delete preference model
  library/catalog/migrations/0001_initial.py
  library/catalog/models.py
Labels: Task

#266 Code refactor
  library/catalog/forms.py
  library/catalog/models.py
  library/catalog/templates/book-details.html
  library/catalog/templates/books.html
  library/catalog/templates/collections.html
  library/catalog/templates/home.html
  library/catalog/templates/profile_bookshelf.html
  library/catalog/views.py
Labels: Task

#271 fix bug
  library/catalog/views.py
Labels: bug

#274 Change base profile UI
  library/catalog/static/css/main.css
  library/catalog/static/js/main.js
  library/catalog/templates/base_profile.html
  library/catalog/templates/change_password.html
  library/catalog/templates/profile_details.html
  library/catalog/templates/profile_edit.html
Labels: Task

#278 Fix unique validation
  library/catalog/static/js/registrationForm.js
Labels: bug

#272 Password recovery
  library/catalog/migrations/0001_initial.py
  library/catalog/static/css/main.css
  library/catalog/static/js/main.js
  library/catalog/templates/base.html
  library/catalog/templates/login_redirect.html
  library/catalog/templates/password_reset.html
  library/catalog/templates/password_reset_complete.html
  library/catalog/templates/password_reset_form.html
  library/catalog/templates/password_reset_sent.html
  library/catalog/templates/reset_password.html
  library/catalog/urls.py
  library/catalog/views.py
  library/library/settings.py
Labels: Task

#287 Admin UI fix
  admin/templates/base.html
Labels: bug

#290 admin - update user password fix
  admin/app.py
  admin/forms.py
Labels: Task, bug

#284 Refactor edit user unique validation
  library/catalog/static/js/editUserForm.js
  library/catalog/urls.py
  library/catalog/views.py
Labels: Task

#286 add admin login flash message
  admin/app.py
Labels: Task, bug

#273 Cache
  library/catalog/models.py
  library/catalog/views.py
Labels: Task

#300 News page
  library/catalog/static/css/main.css
  library/catalog/templates/news_page.html
  library/catalog/views.py
  requirements.txt
Labels: Task

#301 Fixed bug with restore button for admin
  library/catalog/static/js/bookDetails.js
  library/catalog/views.py
Labels: bug

#307 Donate methods
  library/catalog/admin.py
  library/catalog/migrations/0001_initial.py
  library/catalog/models.py
  library/catalog/static/js/payments_metod.js
  library/catalog/templates/cancel.html
  library/catalog/templates/donate_page.html
  library/catalog/templates/success.html
  library/catalog/urls.py
  library/catalog/views.py
  requirements.txt
Labels: Task

#309 # 308 - Swap books from over 1000 pages to the newest books
  library/catalog/templates/collections.html
  library/catalog/views.py
Labels: Task, enhancement
